name: Publish to PYPI
env:
  BRANCH: "main"
  VERSION: ${{ github.sha }}
  LABEL: "RabbitMQ clients"

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: python -m pip install -U pip poetry
    - name: Build
      run: python -m poetry build
#    - name: Publish to Pypi
#      run: python -m poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

    - uses: actions/checkout@v4
    - name: Telegram notification on Failure
      if: failure()
      env:
        MESSAGE: "
          Deploy: FAILED!!!
          \n[${{ env.LABEL}}]: Branch ${{ env.BRANCH }}:
          \n${{ github.event.head_commit.message }}
          \nVersion: ${{ env.VERSION}}

          \n\nRepository: ${{ github.repository }}
          \nSee changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          "
      run: |
        curl \
        -X POST \
        -H 'Content-Type: application/json' \
        -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": false}' \
        https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

    - name: Send notification on Success
      env:
        MESSAGE: "
          Deploy: OK
          \n[${{ env.LABEL}}]: Branch ${{ env.BRANCH }}:
          \n${{ github.event.head_commit.message }}
          \nVersion: ${{ env.VERSION}}

          \n\nRepository: ${{ github.repository }}
          \nSee changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          "
      run: |
        curl \
        -X POST \
        -H 'Content-Type: application/json' \
        -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": true}' \
        https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
