name: Publish to PYPI


on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: python -m pip install -U pip poetry
    - name: Build
      run: python -m poetry build
    - name: Publish to Pypi
      run: python -m poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
